name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.6.3'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run build
      - name: Build project
        run: pnpm run build

      - name: Delete .map files in dist folder
        run: find dist/ -name "*.map" -type f -delete

      # Create release zip
      - name: Create release zip
        run: |
          VERSION=$(node -p "require('./package.json').version")
          RELEASE_NAME="decky-script-runner-v${VERSION}.zip"
          mkdir -p decky-script-runner
          cp -r dist assets package.json plugin.json main.py README.md LICENSE decky-script-runner/
          zip -r $RELEASE_NAME decky-script-runner

      # Upload release artifact
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: decky-script-runner
          path: decky-script-runner-v*.zip
      # Create a GitHub Release and upload the zip file
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0-${{ github.run_number }}
          artifacts: decky-script-runner-v*.zip
